"""empty message

Revision ID: 0665b49766c4
Revises: 
Create Date: 2022-07-03 20:28:48.215011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0665b49766c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.String(length=255), nullable=True),
    sa.Column('start_lat', sa.Numeric(precision=15, scale=10), nullable=True),
    sa.Column('start_lng', sa.Numeric(precision=15, scale=10), nullable=True),
    sa.Column('end', sa.String(length=255), nullable=True),
    sa.Column('end_lat', sa.Numeric(precision=15, scale=10), nullable=True),
    sa.Column('end_lng', sa.Numeric(precision=15, scale=10), nullable=True),
    sa.Column('price', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trips')
    op.drop_table('users')
    # ### end Alembic commands ###
